DROP TABLE IF EXISTS TODO_ITEM;
DROP TABLE IF EXISTS TODO_LIST;
DROP TABLE IF EXISTS USER_ROLES;
DROP TABLE IF EXISTS USERS;
DROP SEQUENCE IF EXISTS global_seq;

CREATE SEQUENCE global_seq START WITH 100;

CREATE TABLE USERS (
  ID        INTEGER PRIMARY KEY DEFAULT nextval('global_seq'),
  USERNAME  VARCHAR(255) NOT NULL,
  PASSWORD  VARCHAR(255) NOT NULL
);

CREATE TABLE USER_ROLES (
  USER_ID   INTEGER,
  ROLE      VARCHAR(20),
  FOREIGN KEY (USER_ID) REFERENCES USERS (ID)
);

CREATE TABLE TODO_LIST (
  ID        INTEGER PRIMARY KEY DEFAULT nextval('global_seq'),
  NAME      VARCHAR(255) NOT NULL,
  OWNER_ID  INTEGER NOT NULL,
  FOREIGN KEY (OWNER_ID) REFERENCES USERS(ID)
);

CREATE TABLE TODO_ITEM (
  ID        INTEGER PRIMARY KEY DEFAULT nextval('global_seq'),
  NAME      VARCHAR(255) NOT NULL,
  LIST_ID   INTEGER NOT NULL,
  FOREIGN KEY (LIST_ID) REFERENCES TODO_LIST(ID)
);

INSERT INTO USERS (USERNAME, PASSWORD)
VALUES ('admin', '$2a$10$tAp5BLhtTBFIDp4MQKjKWuV6zZ6ySRaSsYj5bYkkAEdUMOIss86z6');

INSERT INTO USER_ROLES (USER_ID, ROLE)
VALUES (100, 'ROLE_ADMIN');