DROP TABLE IF EXISTS TODO_ITEM;
DROP TABLE IF EXISTS TODO_LIST;
DROP TABLE IF EXISTS USER_ROLES;
DROP TABLE IF EXISTS USERS;
DROP SEQUENCE IF EXISTS GLOBAL_SEQUENCE;

CREATE TABLE USERS (
  ID        INTEGER(10) NOT NULL AUTO_INCREMENT,
  USERNAME  VARCHAR(255) NOT NULL,
  PASSWORD  VARCHAR(255) NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE USER_ROLES (
  USER_ID   INTEGER(10),
  ROLE      VARCHAR(20),
  FOREIGN KEY (USER_ID) REFERENCES USERS (ID)
);

CREATE TABLE TODO_LIST (
  ID        INTEGER(10) NOT NULL AUTO_INCREMENT,
  NAME      VARCHAR(255) NOT NULL,
  OWNER_ID  INTEGER(10) NOT NULL,
  FOREIGN KEY (OWNER_ID) REFERENCES USERS(ID)
);

CREATE TABLE TODO_ITEM (
  ID        INTEGER(10) NOT NULL AUTO_INCREMENT,
  NAME      VARCHAR(255) NOT NULL,
  LIST_ID   INTEGER(10) NOT NULL,
  FOREIGN KEY (LIST_ID) REFERENCES TODO_LIST(ID)
);

INSERT INTO USERS (USERNAME, PASSWORD)
VALUES ('admin', '$2a$10$tAp5BLhtTBFIDp4MQKjKWuV6zZ6ySRaSsYj5bYkkAEdUMOIss86z6');

